# Generated by Django 4.2.10 on 2024-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
