# Generated by Django 4.2.10 on 2024-03-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
