# Generated by Django 4.2.11 on 2024-03-08 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='tag',
            field=models.CharField(choices=[('update', 'update'), ('delete', 'delete'), ('create', 'create')], default='create', max_length=255),
        ),
        migrations.CreateModel(
            name='RegeneratedImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_image_id', models.PositiveIntegerField()),
                ('original_image_name', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('regenerated_image', models.ImageField(upload_to='regenerated_images')),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('nextregeneration_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
