# Generated by Django 4.2.11 on 2024-03-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_creditpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField()),
                ('type_of_transaction', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('payment_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_credits', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
            ],
        ),
    ]
