# Generated by Django 4.2.11 on 2024-03-11 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_credithistory_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nextregeneration_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 17, 44, 50, 511795)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='regenerated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='frequency_type',
            field=models.CharField(choices=[('week', 'Week'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year'), ('hour', 'Hour'), ('minute', 'Minute')], max_length=25),
        ),
    ]
