# Generated by Django 4.2.11 on 2024-03-12 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_history_image_name_image_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeneratedimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 12, 11, 15, 21, 746174, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regeneratedimage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
