# Generated by Django 4.2.11 on 2024-03-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_credithistory_created_credithistory_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prompt',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
