# Generated by Django 4.2.11 on 2024-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_image_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='frequency_type',
            field=models.CharField(choices=[('week', 'Week'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year'), ('hour', 'Hour'), ('minute', 'Minute'), ('second', 'Second')], max_length=25),
        ),
    ]
