# Generated by Django 4.2.11 on 2024-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_image_frequency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image_data',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='regeneratedimage',
            name='regenerated_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
