# Generated by Django 4.2.11 on 2024-03-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_history_image_data_alter_image_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.BigIntegerField(default=100),
        ),
    ]
