# Generated by Django 4.2.11 on 2024-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_customuser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeneratedimage',
            name='original_image_key_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='regenerated_images', to='home.image'),
            preserve_default=False,
        ),
    ]
