# Generated by Django 4.2.11 on 2024-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_customuser_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credithistory',
            old_name='total_credits',
            new_name='total_credits_deducted',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
