# Generated by Django 4.2.11 on 2024-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_total_credits_credithistory_total_credits_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='credit_balance_left',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
