# Generated by Django 4.2.11 on 2024-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_membership_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_feature_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_feature_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_feature_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_feature_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_feature_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
