# Generated by Django 4.2.11 on 2024-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_membership_membership_feature_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
