# Generated by Django 4.2.11 on 2024-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_paymentrecord_payment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
