# Generated by Django 4.2.10 on 2024-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_history_public_alter_image_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='openai_account',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100)),
                ('key', models.TextField()),
                ('busy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
